[WIP] Add Bonus Unit 5 🚧
huggingface/deep-rl-class pull request #537
Opened 2024-06-05 08:51 UTC by Ivan-267

Adds **Bonus Unit 5. Imitation Learning with Godot RL Agents**

TODO: 
- [ ] Upload and add link for downloading the zip file with starter/completed project.
- [ ] Check all image / video links after course-image repository is updated on HF
- [ ] Review the content and correct any other issues

2024-06-05 08:52 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/deep-rl-course/pr_537). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-06-10 13:07 UTC, simoninithomas requested changes
Hi,

First of all thank you for this excellent tutorial.

There's some small I changes I would like to see:
1️⃣ I put some recommanded changes
Mo̶v̶e̶ ̶y̶o̶u̶r̶ ̶f̶i̶l̶e̶s̶ ̶t̶o̶ ̶u̶n̶i̶t̶ ̶b̶o̶n̶u̶s̶ ̶4̶ ̶s̶i̶n̶c̶e̶ ̶t̶h̶e̶ ̶P̶P̶O̶ ̶b̶o̶n̶u̶s̶ ̶i̶s̶ ̶n̶o̶t̶ ̶r̶e̶a̶d̶y̶ ̶y̶e̶t̶ ̶a̶n̶d̶ ̶w̶e̶ ̶d̶o̶n̶'̶t̶ ̶k̶n̶o̶w̶ ̶w̶h̶e̶n̶ ̶i̶t̶ ̶w̶i̶l̶l̶ ̶b̶e̶ ̶p̶u̶b̶l̶i̶s̶h̶e̶d̶ ̶s̶o̶ ̶f̶o̶r̶ ̶n̶o̶w̶ ̶l̶e̶t̶'̶s̶ ̶a̶l̶l̶ ̶t̶h̶i̶s̶ ̶o̶n̶e̶ ̶b̶o̶n̶u̶s̶ ̶u̶n̶i̶t̶ ̶4̶.̶ -> We don't do that finally because their unit on PPO is almost ready.

I'm preparing the thumbnail and will publish it on this PR so that you can provide your feedback.

2024-06-10 13:07 UTC, simoninithomas commented on units/en/_toctree.yml
> +- title: Bonus Unit 5. Imitation Learning with Godot RL Agents
For now we don't have the future PPO Unit so let's call it bonus unit 4

2024-06-10 13:07 UTC, simoninithomas commented on units/en/unitbonus5/the-environment.mdx
> +- navigate to the key 🔑 and collect it while avoiding falling down into traps, water, or outside the map,
```suggestion
- Navigate to the key 🔑 and collect it while avoiding falling down into traps, water, or outside the map,
```

2024-06-10 13:07 UTC, simoninithomas commented on units/en/unitbonus5/the-environment.mdx
> +- navigate back to the treasure chest in the first room, and open it. Victory! 🏆
```suggestion
- Navigate back to the treasure chest in the first room, and open it. Victory! 🏆
```

2024-06-10 13:07 UTC, simoninithomas commented on units/en/unitbonus5/train-our-robot.mdx
> +You can see a video of the trained agent in <a href="getting-started.mdx">getting started</a>.
I think it's better here to put again the video, instead of moving the readers back to the introduction

2024-06-10 13:14 UTC, simoninithomas commented on units/en/unitbonus5/introduction.mdx
> +
<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>

2024-06-10 13:15 UTC, simoninithomas commented on units/en/unitbonus5/introduction.mdx
> +
```suggestion
<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>
```

2024-06-10 13:15 UTC, simoninithomas commented on units/en/unitbonus5/introduction.mdx
> +
Code is below

2024-06-10 13:15 UTC, simoninithomas commented
Let me know what you think of the thumbnail @Ivan-267 @edbeeching 

<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>

2024-06-13 09:30 UTC, Ivan-267 commented
> Let me know what you think of the thumbnail @Ivan-267 @edbeeching 
> 
> <img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>

Looks great!

2024-06-14 11:59 UTC, Ivan-267 commented
Thanks for your review and making the image, I've sent some additional comments over E-mail.

2024-06-20 08:55 UTC, edbeeching approved these changes
Thanks for iterating on this @Ivan-267 and @simoninithomas , LGTM!

2024-06-20 08:59 UTC, simoninithomas commented
Hi one last update is to put the link of the zip in the course and we're good to publish 🔥

2024-06-20 10:27 UTC, Ivan-267 commented
> Hi one last update is to put the link of the zip in the course and we're good to publish 🔥

Hey, I added the link here:
https://github.com/huggingface/deep-rl-class/blob/dc2c8bf8998efa4f1a5210e1df076abd0836c034/units/en/unitbonus5/getting-started.mdx?plain=1#L3

If you'd like I could change the link to direct link, but I wasn't sure how it works with the server so the current way was the safest.

The newer changes in the PR don't show up in the doc preview.

2024-06-20 12:39 UTC, simoninithomas commented
Yes I just saw I just launch the build PR documentation to check.

For the environmelnt repository I added a PR: https://huggingface.co/ivan267/imitation-learning-tutorial-godot-project/discussions/1

We can publish it this afternoon or any other day you prefer @Ivan-267 ?

2024-06-20 12:45 UTC, simoninithomas commented on units/en/unitbonus5/introduction.mdx
> +<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>
```suggestion
<img src="https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit13/thumbnail.png" alt="Unit bonus 4 thumbnail"/>

```

2024-06-20 12:49 UTC, Ivan-267 commented
> Yes I just saw I just launch the build PR documentation to check. But your link is correct
> 
> For the environmelnt repository I added a PR: https://huggingface.co/ivan267/imitation-learning-tutorial-godot-project/discussions/1
> 
> We can publish it this afternoon or any other day you prefer @Ivan-267 ?

Thanks for adding the readme, I merged it. We can publish it today or whenever is convenient.

2024-06-20 12:55 UTC, simoninithomas commented
Hi what we can do is to publish it this afternoon 🔥  @edbeeching 

What would be nice is:
- A tweet with the video of the robot playing. with the link of the unit.
- Same with Linkedin.

If you want what we can do:

- You write a short tweet on the fact you wrote a unit where people will train this small robot to play plaftorm games using imitation learning
- I reshare with my account and try to reshare with HF account.
- Same for Linkedin.
- I write the announcement on discord by tagging rl people and tagging you.

So that your profile get promoted. But again tell me if you comfortable with that or if you have another idea?

2024-06-20 13:45 UTC, merged